### ISSUE TITLE
Correctly register commands

### ISSUE THREAD

**Issue by AL1L** [customrealms/bukkit-runtime#10]
Although there's no easy way to do it, we need to register the commands correctly in Bukkit with tab complete and everything so that it doesn't show up as red and unknown command. To support more versions, we can use the current system as a fallback.

**Comment by ghost** [comment]
They've added this already.

**Comment by connerdouglass** [comment]
Registering commands is supported by adding them to your project `package.json` file, like this:

```json
{
    "commands": {
        "gmc": {
            "description": "sets your gamemode to creative"
        }
    }
}
```
