### ISSUE TITLE
Default minecraft commands break when a customrealms plugin is added.

### ISSUE THREAD

**Issue by Cron1ca** [customrealms/bukkit-runtime#3]
So everytime I add a customrealms plugin into my server, the default commands like **/gamemode creative** break.

I dont know if im the only one having this issue since I havent seen anyone talk about it

Notw: The server still does register the command, it shows in the cmd, as `{playernamehere} issued server command: /gamemode creative`

**Comment by connerdouglass** [comment]
I think this issue is fixed now, but I'm testing it before I close this issue

**Comment by connerdouglass** [comment]
Okay, I can confirm this issue is resolved. Just run `npm run build:jar` one more time in your project, and the new JAR for your plugin should work correctly. Let me know how it goes!
