### ISSUE TITLE
Plugin JARs break on Linux when built on Windows

### ISSUE THREAD

**Issue by connerdouglass** [customrealms/bukkit-runtime#8]
JAR files built with `crx build` are platform-specific. Building on Windows or Mac and then uploading to a Linux server causes the plugin to crash.

Most people build and test on one of the three platforms locally, then deploy to Linux. So, plugin JARs should bundle either:

- Host platform + Linux, or...
- All three platforms (win, mac, linux)

**Comment by FalcoG** [comment]
The same issue occurs when you build on Linux and try to run it on another machine that is running OpenJDK 17 without OpenJ9.

**Comment by connerdouglass** [comment]
We've updated the runtime to be platform-independent. The same plugin jar file can run on any platform now.
